project:
  type: website
  output-dir: _site

website:
  title: "Featuring Data Science"
  repo-url: https://github.com/dancapellupo/featuring-data-science-web
  page-navigation: true
  navbar:
    left:
      - contents/index.qmd
      - catalog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dancapellupo/featuring-data-science-web
      # - icon: twitter
      #   href: https://twitter.com
  sidebar:
    - id: contents
      style: floating
      collapse-level: 1
      contents:
        - section: "Table of Contents"
          href: contents/index.qmd
          contents:
          - section: "General Data Science"
            contents:
              - contents/data-science-general.qmd
              - contents/data-science-statistics.qmd
          - section: "Feature Selection and Feature Engineering"
            contents:
              - contents/dimensionality-reduction.qmd
          - section: "Supervised Learning"
            contents:
              - contents/supervised.qmd
              - contents/supervised-tree-models.qmd
              - contents/supervised-neural-networks.qmd
          - section: "MLOps"
            contents:
              - contents/mlops.qmd

format:
  html:
    # theme: cosmo, litera, lux, minty, pulse, spacelab, united, yeti
    theme: litera
    css: styles.css
    toc: true


