---
title: "General Topics in Data Science"
listing:
  - id: history
    contents:
    - '../posts/2024-06-10-history-data-science/index.qmd'
    - '../posts/2024-06-10-ml-versus-statistics/index.qmd'
    type: default
  - id: intuition
    contents:
    - '../posts/2024-06-16-data-intuition/index.qmd'
    type: default
    fields: [date, title, description]
  - id: rules
    contents:
    - '../posts/2024-06-05-capital-one-rules-vs-ml/index.qmd'
    - '../posts/2024-06-03-rules-and-ml/index.qmd'
    type: default
    fields: [date, title, description]
page-layout: article
---

## History, Approaching Data Science Problems, and Other General Topics

### History of Data Science

While many of the elements of data science have been around for a long time
(even the idea of machine learning, AI, and the perceptron date back to the
1950s), the profession of data science / data scientist seems to have emerged
around 2008.

This first article below goes through the history of data science, including
its consituent parts - statistics, data analysis, machine learning, data
science tools.

*As a disclaimer, while most of the posts on this website are not connected to
the curator of this site, this is one post authored by myself.*

With two big components of modern data science being statistics and machine
learning, it is useful to think about the differences between the two,
especially to understand different peoples’ approach to a problem. The way a
statistician-by-training might approach a problem will likely be different than
the way a machine learning practitioner will approach that same problem.
<br>
<br>

:::{#history}
:::

### Approaching Data Science Problems

While it may seem strange to discuss this when *data* and *science* are in the
name, there is some amount of *intuition* that comes into play in data science,
and certainly when analyses and results are handed over to people / teams who
are more on the business side of things.

Here below, I summarize three blog posts that try to tackle this idea of
*intuition* in data science. It is important to think about where intuition
most often is relied upon and how much practitioners rely on it.
<br>
<br>

:::{#intuition}
:::

### Rules-Based Engines to Machine Learning

Two articles below describe considerations when considering whether to
transition completely from a more traditional rules-based approach to machine
learning, or a combination of the two.
<br>
<br>

:::{#rules}
:::

You can read about a recent, real-life use case of combining rules with ML from
Netflix in the
[section on neural networks](supervised-neural-networks.qmd#real-life-use-cases-of-neural-networks).

