---
title: "Statistics"
listing:
  - id: stat-sig
    contents: '../posts/2024-06-11-guinness-student-t-test/index.qmd'
    type: default
  - id: top-8
    contents:
    - '../posts/2024-06-11-most-important-statistics-50-years/index.qmd'
    type: default
page-layout: article
---

## Statistics Topics for Data Scientists

### Statistical Significance

As data scientists, sometimes are analysis requires assessing statistical
significance. Maybe it is an A/B test, and we need to determine if one option
is actually better at achieving whatever KPI we might be after.

Perhaps the most common test for statistical significance is the Student's
t-test, and it all started at Guinness:
<br>
<br>

:::{#stat-sig}
:::

### General Topics

This first article is a paper by a statistics professor and a computer science
professor about what they consider to be the most important ideas in statistics
from the past half-century. Some of these topics will look familiar to data
scientists, like regularization. This follows nicely from the previous page,
continuing to look at the connections between statistics and machine learning.
<br>
<br>

:::{#top-8}
:::

